// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4A3h_NctZbgdClhXSHewHClNaNJNdxs',
    appId: '1:523779007893:web:25f21cd424d7e805d1429c',
    messagingSenderId: '523779007893',
    projectId: 'gigzy-639da',
    authDomain: 'gigzy-639da.firebaseapp.com',
    storageBucket: 'gigzy-639da.firebasestorage.app',
    measurementId: 'G-2P81TQXG4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_277LaKTch0PfAQNnmz7jysWORVVQlMw',
    appId: '1:523779007893:android:63981ff837946313d1429c',
    messagingSenderId: '523779007893',
    projectId: 'gigzy-639da',
    storageBucket: 'gigzy-639da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv5JhKYhtBz3C9Nn9_aT26dbmcb0KyRDg',
    appId: '1:523779007893:ios:e0d272747364a5ead1429c',
    messagingSenderId: '523779007893',
    projectId: 'gigzy-639da',
    storageBucket: 'gigzy-639da.firebasestorage.app',
    iosBundleId: 'com.gigshield.gigshieldWorker',
  );

}